#!/usr/bin/env bash
# history-in-prose.test.sh — regression test for the history-in-prose
# detector (precedent: control-char-scrub.test.sh).
#
# The detector's whole value is WHERE it looks: the same identifier is a
# finding in a paragraph and silence in a fenced block, an inline code span,
# an HTML comment, a spec, or a shell command. So every exemption below is
# paired with the positive control that proves the fixture is not vacuous —
# an exemption that passes because its fixture never carried a marker would
# hide the day the marker stops being seen at all.
#
# Fixture markers are written as placeholders and substituted in, so this
# file's own comments carry none of what the detector hunts.
#
# Hermetic: reads the repo only; no gc, no city, no network.

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$HERE/.."
[ -d "$REPO/doctor" ] || REPO="$HERE/../.."
DETECTOR="$REPO/tools/lint-learned.d/history-in-prose.sh"

PASS=0; FAIL=0
ok()  { PASS=$((PASS + 1)); printf '  ok    %s\n' "$1"; }
bad() { FAIL=$((FAIL + 1)); printf '  FAIL  %s\n        %s\n' "$1" "$2"; }
eq()  { if [ "$1" = "$2" ]; then ok "$3"; else bad "$3" "got '$1' want '$2'"; fi; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

if [ -x "$DETECTOR" ]; then ok "detector is executable"
else bad "detector is executable" "not found at $DETECTOR"; exit 1; fi

# Placeholders, resolved after each fixture is written.
fill() {
    sed -e "s|BEADID|tk-4x9qp|g" -e "s|OTHERID|sl-7m2kd|g" -e "s|GCBEAD|gc-8zdml1|g" \
        -e "s|ISODATE|2026-08-13|g" -e "s|LONGDATE|August 13, 2026|g" \
        -e "s|PRREF|#490|g" -e "s|PULLREF|pull/490|g" "$1" > "$1.filled"
    mv "$1.filled" "$1"
}

# Path exemptions read the path the detector is GIVEN, so every case runs
# from the fixture root with a relative path, the way the runner passes them.
run()   { ( cd "$TMP" && "$DETECTOR" "$@" ); }
nfind() { run "$@" | grep -c . || true; }
rc()    { ( cd "$TMP" && "$DETECTOR" "$@" >/dev/null 2>&1 ); echo $?; }

mkdir -p "$TMP/docs" "$TMP/specs" "$TMP/notes/tk-4x9qp" "$TMP/agents" "$TMP/det"

echo "── 1. the three markers, in markdown prose ──"
cat > "$TMP/docs/markers.md" <<'MD'
# Title

A paragraph citing BEADID as the reason.

Another about PRREF and the ruling it settled.

A third at PULLREF for the record.

Measured on ISODATE against the live city.

Shipped LONGDATE, after two rounds.
MD
fill "$TMP/docs/markers.md"
eq "$(nfind docs/markers.md)" "5" "all five marker spellings are found"
eq "$(rc docs/markers.md)" "1" "findings exit 1"
eq "$(run docs/markers.md | sed -n '1s/:.*//p')" "docs/markers.md" "finding names the file"
eq "$(run docs/markers.md | sed -n '1s/^[^:]*:\([0-9]*\):.*/\1/p')" "3" "finding names the line"
case "$(run docs/markers.md | head -1)" in
    *"learned rule: history-in-prose"*) ok "message names the learned rule" ;;
    *) bad "message names the learned rule" "$(run docs/markers.md | head -1)" ;;
esac

echo "── 2. markdown structure, each against its control ──"
cat > "$TMP/docs/fenced.md" <<'MD'
Prose that cites nothing.

```bash
gc bd show BEADID --json
echo "verified ISODATE"
```

Closing prose, also clean.
MD
fill "$TMP/docs/fenced.md"
eq "$(nfind docs/fenced.md)" "0" "a fenced code block is not prose"

cat > "$TMP/docs/unfenced.md" <<'MD'
gc bd show BEADID --json
echo "verified ISODATE"
MD
fill "$TMP/docs/unfenced.md"
eq "$(nfind docs/unfenced.md)" "2" "control: the same two lines unfenced ARE prose"

cat > "$TMP/docs/spans.md" <<'MD'
Resume the branch named `BEADID` before you push.

Resume the branch named BEADID before you push.
MD
fill "$TMP/docs/spans.md"
eq "$(nfind docs/spans.md)" "1" "an inline code span is an argument, the bare token is a citation"

cat > "$TMP/docs/anchors.md" <<'MD'
<!-- src:pr:PRREF:review:r3854321589 adopted:ISODATE -->
- A rule bullet stating what is true now.

<!--
  rule:BEADID src:PULLREF
  adopted:ISODATE
-->
- Another bullet.

But BEADID out here in the body is a citation.
MD
fill "$TMP/docs/anchors.md"
eq "$(nfind docs/anchors.md)" "1" "HTML comments carry the learning anchors; the body does not"

echo "── 3. where history is correct ──"
for p in specs/note.md notes/tk-4x9qp/note.md docs/CHANGELOG.md; do
    cat > "$TMP/$p" <<'MD'
Closed on ISODATE by BEADID, per PRREF.
MD
    fill "$TMP/$p"
    eq "$(nfind "$p")" "0" "exempt: $p"
done
cat > "$TMP/docs/plain.md" <<'MD'
Closed on ISODATE by BEADID, per PRREF.
MD
fill "$TMP/docs/plain.md"
eq "$(nfind docs/plain.md)" "1" "control: the same line under docs/ IS a finding"

cat > "$TMP/docs/gen.ts" <<'TS'
/**
 * This file was auto-generated by openapi-typescript.
 */
/** @description absent for now; PRREF follow-up. */
TS
fill "$TMP/docs/gen.ts"
eq "$(nfind docs/gen.ts)" "0" "a generated header exempts the file"

cat > "$TMP/docs/handwritten.ts" <<'TS'
/**
 * This file is maintained by hand.
 */
/** @description absent for now; PRREF follow-up. */
TS
fill "$TMP/docs/handwritten.ts"
eq "$(nfind docs/handwritten.ts)" "1" "control: the same comment without the marker IS a finding"

echo "── 4. source files: comments, never code ──"
cat > "$TMP/script.sh" <<'SH'
#!/usr/bin/env bash
# Re-claim is fenced against the double-dispatch (BEADID).
echo "closing BEADID"
COUNT="${#ITEMS[@]}"
printf '%s\n' "$#"
gc bd show BEADID --json | sed 's|x|y|'
SH
fill "$TMP/script.sh"
eq "$(nfind script.sh)" "1" "only the comment line is prose"
eq "$(run script.sh | sed -n '1s/^[^:]*:\([0-9]*\):.*/\1/p')" "2" "and it is the comment's line"

echo "── 5. a prefix that is also a namespace ──"
cat > "$TMP/ns.sh" <<'SH'
# The pack is gc-toolkit, the rig is gc-toolkit, the board is gc-visit.
# The bead behind it is GCBEAD.
SH
fill "$TMP/ns.sh"
eq "$(nfind ns.sh)" "1" "gc- command names pass, a gc- bead id does not"

cat > "$TMP/ptr.sh" <<'SH'
# Design authority: specs/BEADID/design-doc.md.
# Superseded in part by BEADID, which is why this exists.
SH
fill "$TMP/ptr.sh"
eq "$(nfind ptr.sh)" "1" "a path into specs points at the record; the bare id cites it"

echo "── 6. the allow file ──"
cp "$DETECTOR" "$TMP/det/history-in-prose.sh"
chmod +x "$TMP/det/history-in-prose.sh"
printf '%s\n' 'the one instruction that must name it' > "$TMP/det/history-in-prose.allow"
cat > "$TMP/docs/allowed.md" <<'MD'
Pass BEADID: the one instruction that must name it.

Any other line naming OTHERID stays a finding.
MD
fill "$TMP/docs/allowed.md"
eq "$(nfind docs/allowed.md)" "2" "without an allow file both lines are findings"
eq "$( ( cd "$TMP" && ./det/history-in-prose.sh docs/allowed.md ) | grep -c . || true)" "1" \
   "an allow regex suppresses its line and only its line"

echo "── 7. a clean tree is a clean pass ──"
cat > "$TMP/docs/clean.md" <<'MD'
# Heading with 4 items

State what is true now, and nothing about how it got here.
MD
eq "$(nfind docs/clean.md)" "0" "no markers, no findings"
eq "$(rc docs/clean.md)" "0" "clean exits 0"
eq "$(rc docs/clean.md docs/markers.md)" "1" "one dirty file fails the set"

printf '\n%s passed, %s failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
