#!/usr/bin/env bash
# Pack doctor check: docs/seed-audit/ still matches the fragments it renders.
#
# WHAT THE ARTIFACT IS. docs/seed-audit/ holds the full rendered standing prompt
# of every agent this pack configures and the compiled recipe of every formula it
# exposes — the part of the spawn seed this repo controls, committed so it can be
# reviewed and diffed as one thing. It is generated by
# assets/scripts/render-seed-audit.sh; nothing about it is hand-maintained.
#
# WHY IT NEEDS A CHECK AT ALL. A golden file over generated text is only worth
# anything while it is current. Stale, it is worse than absent: it reads as an
# authoritative statement of what agents receive while describing a seed nobody
# has been given for weeks, and the staleness is invisible — every file in it
# still looks like a perfectly good prompt. The pre-commit hook in assets/hooks/
# regenerates on any commit that touches the inputs, so in the ordinary case this
# check never fires. It exists for the commits that bypass hooks: a GitHub web
# edit, `git commit --no-verify`, an agent in a checkout where core.hooksPath was
# never set, or a rig whose hooks are disabled outright (gascity runs with
# core.hooksPath=/dev/null for host-capacity reasons).
#
# WHY THIS CHECK IS CHEAP AND NOT AUTHORITATIVE. A full re-render is ~44 `gc`
# invocations and 15-25 s, which is too much to spend on every `gc doctor`. So
# this compares DIGESTS: INDEX.md records a sha256 over every input file that
# feeds the render, and the check recomputes it from the pack tree. That answers
# "did an input move without the artifact moving" — which is the failure mode —
# without rendering anything. The authoritative check, when you want certainty,
# is the renderer's own:
#
#     assets/scripts/render-seed-audit.sh --check
#
# WHY A gc VERSION MISMATCH IS ONLY A WARNING. Prompt composition lives in the gc
# binary, not only in this repo. Upgrading gc can move every byte of the artifact
# with no commit here to explain it, and failing a repo's health check on the
# host's binary version is the "CI fails for reasons nobody controls" trap this
# artifact was scoped to avoid. So: content mismatch is an error, version drift
# is a warning that says re-render.
#
# WHY AN UNINSTALLED HOOK IS ALSO A WARNING. core.hooksPath is not set by
# cloning. A checkout without it has no mechanism keeping the artifact current at
# all, so the audit will go stale and this check will only notice on the next
# doctor run. Reporting it is what stops "the check passed" from being read as
# "the loop is closed".
#
# Exit codes: 0=OK, 1=Warning, 2=Error
# stdout: first line=message, rest=details

set -u

dir="${GC_PACK_DIR:-.}"
audit="$dir/docs/seed-audit"
index="$audit/INDEX.md"
script="$dir/assets/scripts/render-seed-audit.sh"

if [ ! -x "$script" ]; then
    echo "OK: no render-seed-audit.sh in this pack — nothing to keep current"
    exit 0
fi

if [ ! -f "$index" ]; then
    echo "The seed audit is MISSING — docs/seed-audit/INDEX.md does not exist"
    echo "assets/scripts/render-seed-audit.sh ships in this pack, so the artifact it"
    echo "generates is expected to be committed alongside it. Without the artifact the"
    echo "script is unreachable documentation: nothing shows what any agent receives,"
    echo "and nothing detects when a fragment change moves it."
    echo ""
    echo "Fix: assets/scripts/render-seed-audit.sh && git add docs/seed-audit"
    exit 2
fi

recorded_digest="$(sed -n 's/^- source digest: `\(.*\)`$/\1/p' "$index" | head -1)"
recorded_gcver="$(sed -n 's/^- `gc` version: `\(.*\)`$/\1/p' "$index" | head -1)"

if [ -z "$recorded_digest" ]; then
    echo "The seed audit records no source digest — staleness is UNVERIFIABLE"
    echo "docs/seed-audit/INDEX.md exists but carries no '- source digest: \`…\`' line."
    echo "Either it was hand-edited or it was written by an older renderer. Regenerate"
    echo "it so the artifact can be checked at all."
    echo ""
    echo "Fix: assets/scripts/render-seed-audit.sh && git add docs/seed-audit"
    exit 2
fi

# --print-digest hashes files and shells out to nothing; it works on a host with
# no gc binary, which is why the version lives on its own INDEX line rather than
# inside the digest.
actual_digest="$("$script" --root "$dir" --print-digest 2>/dev/null)"
if [ -z "$actual_digest" ]; then
    echo "Could not recompute the seed-audit source digest — staleness is UNVERIFIED"
    echo "$script --print-digest produced no output."
    echo "This is not a benign skip: it means the one cheap staleness signal is dark."
    exit 1
fi

details=""
add_detail() { details="${details}${1}
"; }

if [ "$recorded_digest" != "$actual_digest" ]; then
    echo "The seed audit is STALE — a prompt input moved without the artifact moving"
    echo "recorded digest: $recorded_digest"
    echo "actual digest:   $actual_digest"
    echo ""
    echo "One or more of agents/, template-fragments/, formulas/, packs/ or pack.toml"
    echo "changed since docs/seed-audit/ was generated, so the committed audit now"
    echo "describes a seed no agent receives. Every file in it still reads as a valid"
    echo "prompt, which is exactly why this needs a check rather than a review."
    echo ""
    echo "Fix: assets/scripts/render-seed-audit.sh && git add docs/seed-audit"
    exit 2
fi

rc=0

if command -v gc >/dev/null 2>&1; then
    actual_gcver="$(gc version 2>/dev/null | head -1)"
    if [ -n "$actual_gcver" ] && [ -n "$recorded_gcver" ] && [ "$actual_gcver" != "$recorded_gcver" ]; then
        add_detail "gc version drift: artifact rendered with $recorded_gcver, host runs $actual_gcver."
        add_detail "Prompt composition lives in the binary, so the rendered text may have moved"
        add_detail "with no change in this repo. Re-render to refresh: assets/scripts/render-seed-audit.sh"
        rc=1
    fi
fi

# The hook is what keeps the artifact current between doctor runs. Report it
# from the pack's own checkout, not from GC_PACK_DIR's git config alone: a linked
# worktree shares core.hooksPath with the common dir, so asking git here is the
# same question the committing worktree will answer.
if command -v git >/dev/null 2>&1 && git -C "$dir" rev-parse --git-dir >/dev/null 2>&1; then
    hookspath="$(git -C "$dir" config --get core.hooksPath 2>/dev/null)"
    if [ "$hookspath" != "assets/hooks" ]; then
        if [ -z "$hookspath" ]; then
            add_detail "core.hooksPath is unset in this checkout, so assets/hooks/pre-commit never runs."
        else
            add_detail "core.hooksPath is \"$hookspath\", not assets/hooks, so assets/hooks/pre-commit never runs."
        fi
        add_detail "Nothing regenerates the audit on commit; it will go stale silently between"
        add_detail "doctor runs. Wire it up: assets/scripts/render-seed-audit.sh --install-hook"
        add_detail "(Deliberate on a rig that disables hooks for host capacity — gascity sets"
        add_detail "core.hooksPath=/dev/null on purpose. There, this check IS the mechanism.)"
        rc=1
    fi
fi

n_agents="$(find "$audit/agents" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')"
n_formulas="$(find "$audit/formulas" -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')"

if [ "$rc" -eq 0 ]; then
    echo "OK: seed audit current — $n_agents agent prompt(s), $n_formulas formula recipe(s), digest $(printf %.12s "$actual_digest"), hook wired"
    exit 0
fi

echo "Seed audit content is current ($n_agents agents, $n_formulas formulas) but its upkeep is not fully wired"
printf '%s' "$details"
exit 1
